#!/usr/bin/env node
// Detection harness for /qrspi/8_cleanup_docstrings (generic port of cleanup-docstrings).
// Scans branch-vs-base changed files for dev-process cruft inside comments/docstrings,
// and lists temp planning docs (thoughts/qrspi) the branch touched. Detection only — never edits.
// Output: human report (default) or JSON (--json) for the agent to turn into a diff proposal.
//
// Usage:
//   node driver.mjs [--base <ref>] [--json]
//   CLEANUP_BASE=<ref> node driver.mjs
// Default base: origin/HEAD if resolvable, else main.

import { execFileSync } from 'node:child_process';
import { readFileSync, existsSync } from 'node:fs';

const args = process.argv.slice(2);
const json = args.includes('--json');
const git = (a) => execFileSync('git', a, { encoding: 'utf8' }).trim();

const base = (() => {
  const i = args.indexOf('--base');
  if (i >= 0 && args[i + 1]) return args[i + 1];
  if (process.env.CLEANUP_BASE) return process.env.CLEANUP_BASE;
  try {
    return git(['symbolic-ref', 'refs/remotes/origin/HEAD']).replace('refs/remotes/origin/', '');
  } catch {
    return 'main';
  }
})();

let changed;
try {
  changed = git(['diff', '--name-only', `${base}...HEAD`]).split('\n').filter(Boolean);
} catch (e) {
  console.error(`git diff failed against base '${base}': ${e.message}`);
  process.exit(2);
}

// Code files we scan for comment cruft.
const CODE = /\.(rs|ts|tsx|js|jsx|mjs|cjs|py|go|java|kt|c|cc|cpp|h|hpp|rb|php|swift|html|toml|yaml|yml)$/;
// Temp planning docs (dev-process artifacts QRSPI created for reference).
const TEMP_DOC = /(^|\/)(thoughts|\.qrspi)\//i;

const codeFiles = changed.filter((f) => CODE.test(f) && existsSync(f));
const tempDocs = changed.filter((f) => TEMP_DOC.test(f));

// A line counts as a comment if it carries a comment marker. Keeps us off code/string literals.
const COMMENT = /(^\s*(\/\/!?|\/\/\/|\/\/|#|\*|<!--|"""|''')|\/\/|#\s|<!--)/;

// Cruft categories. Each: {tag, re, why}. re tested against the comment line.
const RULES = [
  {
    // exclude decimals (e.g. `step 0.001`) via (?!\.\d)
    tag: 'phase',
    re: /\b(phase|step|wave|milestone|iteration|sprint)\s*#?\d+\b(?!\.\d)/i,
    why: 'dev-stage marker — describe what the code does, drop the stage label',
  },
  {
    tag: 'phase',
    re: /\b(PR|task|ticket|issue)\s*#?\d+\b/i,
    why: 'dev-tracking ref — not meaningful to a future reader of the code',
  },
  {
    tag: 'temp-ref',
    re: /(thoughts\/|\bqrspi\b|\b(plan|design|structure|research|questions|task)\.md\b|NOTES\.md|scratch\.md)/i,
    why: 'points at a temp/planning doc — inline the relevant fact, drop the pointer',
  },
  {
    tag: 'decision',
    re: /\b(decision:|chose .+ over |as decided\b|per (the )?(plan|design|review|spec)\b|see (the )?(plan|design|structure|research)\b)/i,
    why: 'design-decision residue — keep only the invariant/why, drop process narration',
  },
  {
    // `claude code` / `by claude`, never bare CLAUDE.md (a legit permanent-doc ref)
    tag: 'ai-tag',
    re: /\b(AI[- ]?agent|auto-?generated by|co-authored-by|TODO\(agent\)|claude code\b|by claude\b)/i,
    why: 'AI-authorship residue — remove',
  },
];

const findings = [];
for (const f of codeFiles) {
  const lines = readFileSync(f, 'utf8').split('\n');
  lines.forEach((line, i) => {
    if (!COMMENT.test(line)) return;
    for (const r of RULES) {
      if (r.re.test(line)) {
        findings.push({ file: f, line: i + 1, tag: r.tag, text: line.trim(), why: r.why });
        break; // one finding per line
      }
    }
  });
}

if (json) {
  console.log(JSON.stringify({ base, findings, tempDocs }, null, 2));
  process.exit(0);
}

// Human report.
const byTag = findings.reduce((m, f) => ((m[f.tag] ??= []).push(f), m), {});
console.log(`cleanup-docstrings — base ${base}, ${codeFiles.length} code files scanned\n`);
if (!findings.length) console.log('No docstring cruft found.\n');
for (const [tag, fs] of Object.entries(byTag)) {
  console.log(`## ${tag}  (${fs.length})  — ${fs[0].why}`);
  for (const x of fs) console.log(`  ${x.file}:${x.line}  ${x.text}`);
  console.log('');
}

console.log('## temp planning docs');
if (tempDocs.length) {
  console.log('  touched on branch (offer to remove/archive after PR prep, confirm first):');
  for (const d of tempDocs) console.log(`    ${d}`);
} else {
  console.log('  none on branch');
}
console.log(`\nTotal findings: ${findings.length}`);
